### ISSUE TITLE
Crash when calling `ComposedDataSource.removeAll`

### ISSUE THREAD

**Issue by JosephDuffy** [shaps80/Composed#4]
I have a feeling this will also crash with a regular `remove(dataSource:)` call for the last section, but this is how I came across it.

`ComposedDataSource.removeAll` calls `updateDelegate?.dataSource(self, didDeleteSections: IndexSet(indexes))` on line 164, which triggers `collectionView.collectionViewLayout.layoutAttributesForElements(in: collectionView.bounds)
` in `CollectionViewWrapper`.

`FlowLayout` is then queried, but the collection view and the data sources are out-of-sync. The collection view thinks it has more than 0 sections, but they've actually just been deleted, so when `backgroundViewClass(in:forSectionAt:)` is called it tries to get a mapping for a section that – to the data source – doesn't exist.

I've seen this on `master` and `performance` but my attempts to fix it have been fruitless :(

Attached is a screenshot of the stacktrace.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/1325813/56974046-9d7f3180-6b5d-11e9-90d5-9265435ec444.png">

**Comment by shaps80** [comment]
Interesting. I think I might have an idea about this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
Cheers

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
I'll test this against #5

**Comment by shaps80** [comment]
@JosephDuffy 

Ok, this is now fixed and I can see how I introduced the issue. Let me try to explain.

When we mutate a `ComposedDataSource` we need to call `invalidate` which remaps all of its children, to ensure internal consistency.

`removeAll` however was using the same call to `_remove(dataSource:)`. This would ultimately cause an invalidation, which would mean that in most cases, the internal consistency was now out-of-date during the update for multiple sections. I noticed it immediately on debugging, because I had duplicate section indexes, which didn't make sense. We store these in an IndexSet, which would de-dupe for us, but then we'd have an incorrect number of sections to delete.

So, I now explicitly call `invalidate` _after_ we have already removed all associated mappings, and I've updated the single call `remove` to do the same. Now appears to be working nicely again.
